"""
Portfolio Health Check Agent.

Receives a user profile dict.
Fetches live prices via yfinance.
Returns a PortfolioHealthResponse dict.

Edge cases handled:
  - Empty portfolio (usr_004)  → build guidance, no crash
  - Multi-currency positions   → normalised to USD via yfinance FX
  - Concentration risk         → flags high/medium/low
  - Retiree / income-focus     → income-specific observations
"""
from __future__ import annotations
import datetime
import logging
from typing import Any

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This analysis is generated by an AI system for informational purposes only. "
    "It does not constitute investment advice, a solicitation, or a recommendation "
    "to buy or sell any security. Past performance is not indicative of future results. "
    "Please consult a qualified financial adviser before making any investment decisions."
)

BENCHMARK_TICKERS = {
    "S&P 500":    "^GSPC",
    "QQQ":        "QQQ",
    "FTSE 100":   "^FTSE",
    "NIKKEI 225": "^N225",
    "MSCI World": "URTH",
}

FX_PAIRS = {
    "EUR": "EURUSD=X",
    "GBP": "GBPUSD=X",
    "JPY": "JPYUSD=X",
    "SGD": "SGDUSD=X",
}


def _fetch_price(ticker: str) -> float | None:
    """Fetch latest closing price via yfinance. Returns None on failure."""
    try:
        import yfinance as yf
        hist = yf.Ticker(ticker).history(period="5d")
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception as exc:
        logger.warning("yfinance fetch failed for %s: %s", ticker, exc)
        return None


def _to_usd(amount: float, currency: str) -> float:
    """Convert amount in `currency` to USD."""
    if currency == "USD":
        return amount
    pair = FX_PAIRS.get(currency)
    if not pair:
        logger.warning("Unknown currency %s, treating as USD", currency)
        return amount
    rate = _fetch_price(pair)
    if rate is None:
        logger.warning("Could not fetch FX rate for %s, treating as 1:1", currency)
        return amount
    return amount * rate


def _benchmark_return(benchmark_name: str, earliest_date: str) -> float:
    """Approximate benchmark % return from earliest_date to today."""
    try:
        import yfinance as yf
        ticker = BENCHMARK_TICKERS.get(benchmark_name, "^GSPC")
        hist = yf.Ticker(ticker).history(
            start=earliest_date, period="max"
        )
        if hist.empty or len(hist) < 2:
            return 0.0
        price_start = float(hist["Close"].iloc[0])
        price_end   = float(hist["Close"].iloc[-1])
        return round((price_end - price_start) / price_start * 100, 2)
    except Exception as exc:
        logger.warning("Benchmark fetch failed for %s: %s", benchmark_name, exc)
        return 0.0


def _annualised(total_pct: float, start_date: str) -> float:
    """Annualise a total return given an investment start date."""
    try:
        start = datetime.datetime.strptime(start_date, "%Y-%m-%d")
        years = (datetime.datetime.today() - start).days / 365.25
        if years <= 0:
            return total_pct
        return round(((1 + total_pct / 100) ** (1 / years) - 1) * 100, 2)
    except Exception:
        return total_pct


def run(user: dict[str, Any], llm: Any = None) -> dict[str, Any]:
    """
    Run the Portfolio Health agent.

    Parameters
    ----------
    user : User profile dict (matches UserProfile schema).
    llm  : Accepted but not used — this agent does pure computation.
           Kept so the test harness can pass mock_llm uniformly.

    Returns
    -------
    dict matching PortfolioHealthResponse schema.
    Never raises — all errors are caught and logged.
    """
    positions     = user.get("positions", [])
    prefs         = user.get("preferences") or {}
    benchmark_name = prefs.get("preferred_benchmark", "S&P 500")
    income_focus  = prefs.get("income_focus", False)

    # ── Empty portfolio ───────────────────────────────────────────────────────
    if not positions:
        return {
            "concentration_risk": {
                "top_position_pct":    0.0,
                "top_3_positions_pct": 0.0,
                "flag": "low",
            },
            "performance": {
                "total_return_pct":      0.0,
                "annualized_return_pct": 0.0,
            },
            "benchmark_comparison": {
                "benchmark":             benchmark_name,
                "portfolio_return_pct":  0.0,
                "benchmark_return_pct":  0.0,
                "alpha_pct":             0.0,
            },
            "observations": [
                {
                    "severity": "info",
                    "text": (
                        "Your account is verified and ready to invest. "
                        "Consider starting with a diversified low-cost index fund "
                        "such as VOO (S&P 500) or VT (global) to build a solid foundation."
                    ),
                },
                {
                    "severity": "info",
                    "text": (
                        "Before investing, define your goal, time horizon, and risk tolerance. "
                        "Keep 3–6 months of expenses in cash before deploying capital."
                    ),
                },
            ],
            "disclaimer": DISCLAIMER,
            "build_guidance": (
                "You have no positions yet — great time to start. "
                "A diversified global ETF (e.g. VWRA or VT) is one of the simplest "
                "first investments for a moderate-risk investor."
            ),
        }

    # ── Fetch live prices ─────────────────────────────────────────────────────
    enriched       = []
    total_cost_usd  = 0.0
    total_value_usd = 0.0
    earliest_date   = "2099-12-31"

    for pos in positions:
        ticker       = pos["ticker"]
        qty          = pos["quantity"]
        avg_cost     = pos["avg_cost"]
        currency     = pos.get("currency", "USD")
        purchased_at = pos.get("purchased_at", "2020-01-01")

        cost_usd  = _to_usd(avg_cost * qty, currency)
        live_px   = _fetch_price(ticker) or avg_cost
        value_usd = _to_usd(live_px * qty, currency)

        enriched.append({
            "ticker":       ticker,
            "cost_usd":     cost_usd,
            "value_usd":    value_usd,
            "purchased_at": purchased_at,
        })

        total_cost_usd  += cost_usd
        total_value_usd += value_usd

        if purchased_at < earliest_date:
            earliest_date = purchased_at

    if total_value_usd == 0:
        total_value_usd = 1   # guard div/0

    # ── Concentration risk ────────────────────────────────────────────────────
    enriched.sort(key=lambda x: x["value_usd"], reverse=True)

    top1_pct = round(enriched[0]["value_usd"] / total_value_usd * 100, 1)
    top3_pct = round(
        sum(p["value_usd"] for p in enriched[:3]) / total_value_usd * 100, 1
    )

    if top1_pct >= 50:
        conc_flag = "high"
    elif top1_pct >= 30:
        conc_flag = "medium"
    else:
        conc_flag = "low"

    # ── Performance ───────────────────────────────────────────────────────────
    total_return_pct = round(
        (total_value_usd - total_cost_usd) / total_cost_usd * 100, 2
    )
    ann_return_pct = _annualised(total_return_pct, earliest_date)

    # ── Benchmark comparison ──────────────────────────────────────────────────
    bench_return = _benchmark_return(benchmark_name, earliest_date)
    alpha        = round(total_return_pct - bench_return, 2)

    # ── Observations ──────────────────────────────────────────────────────────
    observations = []

    if conc_flag == "high":
        observations.append({
            "severity": "warning",
            "text": (
                f"{enriched[0]['ticker']} makes up {top1_pct}% of your portfolio — "
                "highly concentrated. Consider diversifying to reduce single-stock risk."
            ),
        })
    elif conc_flag == "medium":
        observations.append({
            "severity": "info",
            "text": (
                f"Your top holding ({enriched[0]['ticker']}) is {top1_pct}% of the portfolio. "
                "Moderately concentrated — monitor closely."
            ),
        })

    if top3_pct > 80:
        observations.append({
            "severity": "warning",
            "text": (
                f"Top 3 positions account for {top3_pct}% of your portfolio. "
                "Strong concentration increases volatility and single-stock risk."
            ),
        })

    if alpha > 2:
        observations.append({
            "severity": "info",
            "text": (
                f"Outperforming {benchmark_name} by {alpha}% over the period — well done."
            ),
        })
    elif alpha < -5:
        observations.append({
            "severity": "warning",
            "text": (
                f"Underperforming {benchmark_name} by {abs(alpha)}%. "
                "Consider whether active positions are adding value."
            ),
        })

    if income_focus:
        observations.append({
            "severity": "info",
            "text": (
                "Your portfolio includes dividend-focused holdings. "
                "Ensure dividend income is tracked against your income needs."
            ),
        })

    if total_return_pct >= 0:
        observations.append({
            "severity": "info",
            "text": f"Portfolio is up {total_return_pct:.1f}% since inception.",
        })
    else:
        observations.append({
            "severity": "warning",
            "text": f"Portfolio is down {abs(total_return_pct):.1f}% since inception.",
        })

    if not observations:
        observations.append({
            "severity": "info",
            "text": "Your portfolio looks balanced. Keep monitoring regularly.",
        })

    return {
        "concentration_risk": {
            "top_position_pct":    top1_pct,
            "top_3_positions_pct": top3_pct,
            "flag":                conc_flag,
        },
        "performance": {
            "total_return_pct":      total_return_pct,
            "annualized_return_pct": ann_return_pct,
        },
        "benchmark_comparison": {
            "benchmark":            benchmark_name,
            "portfolio_return_pct": total_return_pct,
            "benchmark_return_pct": bench_return,
            "alpha_pct":            alpha,
        },
        "observations": observations,
        "disclaimer":   DISCLAIMER,
    }